### ISSUE TITLE
Poned las anotaciones JPA

### ISSUE THREAD

**Issue by Lainezz** [LautaroKruck/ProyectoStockControl#1]
https://github.com/LautaroKruck/ProyectoStockControl/blob/48b1c75b74e6d4074033d0d345e5e37a8e9fe2d1/src/main/java/com/es/stockcontrol/model/Producto.java#L6

Hay que completar la clase con todas las anotaciones JPA

**Comment by ManuelAmayaOrozco** [comment]
Añadidas las anotaciones JPA en producto en el último push

**Comment by ManuelAmayaOrozco** [comment]
https://github.com/LautaroKruck/ProyectoStockControl/blob/master/src/main/java/com/es/stockcontrol/model/Producto.java

**Comment by Lainezz** [comment]
Muy bien.
Ponle la anotacion @ Temporal al atributo fecha_alta

**Comment by ManuelAmayaOrozco** [comment]
Ya está añadido, muchas gracias por recordármelo
