### ISSUE TITLE
Cambia el nombre para seguir la notación camel Case

### ISSUE THREAD

**Issue by Lainezz** [LautaroKruck/ProyectoStockControl#3]
https://github.com/LautaroKruck/ProyectoStockControl/blob/0ea571e2853245eb402457774e083eef10b825e6/src/main/java/com/es/stockcontrol/model/User.java#L9

el nombre del atributo debe seguir la notación CamelCase

**Comment by RubenRamIgl** [comment]
Cambiado a CamelCase
